# chart-testing configuration
# https://github.com/helm/chart-testing/blob/main/doc/ct.yaml

# Directories containing charts
chart-dirs:
  - charts

# Additional Helm repositories for dependency resolution
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami

# Helm options
helm-extra-args: --timeout 600s
helm-extra-set-args: --set=global.testMode=true

# Chart schema validation
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true

# Testing options
check-version-increment: true
debug: false

# Target branches for change detection
target-branch: main

# Upgrade testing (disabled for now)
upgrade: false

# Excluded charts from installation testing
# These charts are still linted but not installed during CI
# Reason: DocETL requires custom-built Docker images that aren't publicly available
excluded-charts:
  - docetl
